name: Playwright Changed Tests

on:
  pull_request:
    # Trigger on any changes in the repo
    paths:
      - '**/*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for git diff

      # 2️⃣ Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 3️⃣ Install dependencies
      - run: npm ci

      # 4️⃣ Install Playwright Chromium only
      - run: npx playwright install --with-deps chromium

      # 5️⃣ Detect changed test files against master
      - name: Get changed test files
        id: changed
        run: |
          git fetch origin master
          FILES=$(git diff --name-status origin/master | grep '^tests/.*\.spec\.ts$' | awk '{print $2}' || true)
          echo "files=$FILES" >> $GITHUB_OUTPUT
          echo "Changed test files: $FILES"

      # 6️⃣ Run only changed tests
      - name: Run only changed tests
        if: steps.changed.outputs.files != ''
        run: |
          echo "Running only changed tests..."
          npx playwright test ${{ steps.changed.outputs.files }}

      # 7️⃣ Optional: skip if no tests changed
      - name: No tests changed
        if: steps.changed.outputs.files == ''
        run: echo "No test files changed. Skipping Playwright run."
